import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppBar, Button, Toolbar, Typography } from "@mui/material";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppBar position="static">
          <Toolbar>
            <Typography variant="h6" sx={{ flexGrow: 1 }}>
              Disaster Dashboard
            </Typography>
            <Button color="inherit" component={Link} href="/">
              Dashboard
            </Button>
            <Button color="inherit" component={Link} href="/latest-news">
              Latest News
            </Button>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
